# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EarthQuakeGuide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for EarthQuakeGuide
  pod "AFNetworking"
  
  target 'EarthQuakeGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EarthQuakeGuideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
